FROM python:3.11-slim
WORKDIR /app
COPY platform-core/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY platform-core /app
COPY udoc-station /app/udoc-station
RUN python3 seed.py || true
EXPOSE 8077
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8077"]
